Repository angr/claripy, pull requests merged in 2018-04, with the labels that each got.

#69 Fix bitwise xor simplifier
  claripy/operations.py
Labels: bug

#70 BackendZ3: Store a copy of tactics in TLS.
  claripy/backends/backend_z3.py
Labels: bug

#71 BackendZ3: Add memory pressure for new solvers to make PyPy's GC happy.
  claripy/backends/backend_z3.py
Labels: bug

#75 Reverse ite cases
  claripy/ast/bool.py
  claripy/operations.py
  tests/test_expression.py
Labels: feature

#72 Base._replace() optimization: Short-circuit for 'Or' expressions.
  claripy/ast/base.py
Labels: enhancement

#73 BackendZ3._batch_eval(): Remove the And operator if there is only one expression.
  claripy/backends/backend_z3.py
Labels: enhancement

#74 Pass on the 'invalidate_cache' parameter.
  claripy/frontends/composite_frontend.py
Labels: bug
