Repository angr/claripy, pull requests merged in 2019-06, with the labels that each got.

#144 Balancer: Fix balance_Extract. Add a test case.
  claripy/balancer.py
  tests/test_balancer.py
Labels: bug

#149 Add docstrings to claripy.Frontend
  claripy/frontend.py
Labels: enhancement

#153 BackendConcrete: Add fast paths for is_true(False) and is_false(True).
  claripy/backends/backend_concrete.py
Labels: enhancement

#155 Do not run .convert() on numbers.
  claripy/backends/__init__.py
Labels: enhancement

#152 Add a debug mode to allow users to turn off certain checks for better performance.
  claripy/__init__.py
  claripy/bv.py
  claripy/debug.py
  claripy/operations.py
Labels: feature
