Repository angr/claripy, pull requests merged in 2022-11, with the labels that each got.

#310 ModelCacheMixin: Force all ASTs to exist in the cache before using for max() and min(). Close #309.
  claripy/frontend_mixins/model_cache_mixin.py
  tests/test_expression.py
  tests/test_solver.py
Labels: bug

#306 Replace __pos__ with lambda x: x
  claripy/ast/bv.py
  claripy/operations.py
Labels: enhancement

#313 Only edit signal handling in main thread
  claripy/backends/backend_z3.py
Labels: bug

#304 lint `backend_z3.py`
  claripy/backends/backend_z3.py
Labels: enhancement

#311 Warn on use of true division for BVs
  claripy/ast/bv.py
  claripy/utils/__init__.py
  claripy/utils/deprecated.py
Labels: enhancement

#316 Pass Z3 StringVs with implicit zero pads explicitly
  claripy/backends/backend_z3.py
Labels: bug

#320 CompositeSolver: The merged child solver should be of the transitive closure of variables.
  claripy/frontends/composite_frontend.py
  tests/test_solver.py
Labels: bug

#300 Condense min/max into singular function
  claripy/backends/backend_z3.py
  tests/test_z3.py
Labels: bug, enhancement
